# -*- coding: utf-8 -*-
"""Location_Detection_for_IP_Address.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ipjfF00YZIbJzNYsKNDd22UJpKHSc0_
"""

import pandas as pd
import requests
import time

# ---------------------------
# FUNCTION 1: ARIN RDAP LOOKUP
# ---------------------------
def get_arin_info(ip):
    url = f"https://rdap.arin.net/registry/ip/{ip}"
    try:
        r = requests.get(url, timeout=10).json()

        net_name = r.get("name")
        handle = r.get("handle")
        start = r.get("startAddress")
        end = r.get("endAddress")

        org_name = None
        if "entities" in r:
            for ent in r["entities"]:
                if "roles" in ent and "registrant" in ent["roles"]:
                    org_name = ent.get("vcardArray", [None, []])[1][1][3] if len(ent.get("vcardArray", [])) > 1 else None

        # Abuse contact emails
        abuse_emails = []
        if "entities" in r:
            for ent in r["entities"]:
                if "roles" in ent and "abuse" in ent["roles"]:
                    if "vcardArray" in ent:
                        v = ent["vcardArray"][1]
                        for item in v:
                            if item[0] == "email":
                                abuse_emails.append(item[3])

        return {
            "net_name": net_name,
            "net_handle": handle,
            "startAddress": start,
            "endAddress": end,
            "org_name": org_name,
            "abuse_emails": ",".join(abuse_emails)
        }

    except:
        return {
            "net_name": None,
            "net_handle": None,
            "startAddress": None,
            "endAddress": None,
            "org_name": None,
            "abuse_emails": None
        }


# ---------------------------
# FUNCTION 2: GEOIP LOOKUP (IPinfo Free API)
# ---------------------------
def get_geoip_info(ip):
    try:
        url = f"https://ipinfo.io/{ip}/json"
        r = requests.get(url, timeout=10).json()

        return {
            "country": r.get("country"),
            "region": r.get("region"),
            "city": r.get("city"),
            "latitude_longitude": r.get("loc"),
            "org_from_geoip": r.get("org")
        }
    except:
        return {
            "country": None,
            "region": None,
            "city": None,
            "latitude_longitude": None,
            "org_from_geoip": None
        }


# ---------------------------
# MAIN SCRIPT
# ---------------------------

# Load Excel file
df = pd.read_excel("/content/IP Address_Location_Detected.xlsx")

results = []

for ip in df["IP Address"]:
    print(f"Processing IP: {ip}")

    arin_data = get_arin_info(ip)
    geo_data = get_geoip_info(ip)

    row = {"ip": ip}
    row.update(arin_data)
    row.update(geo_data)

    results.append(row)

    time.sleep(1)  # avoid API rate limit

# Convert to DataFrame
output_df = pd.DataFrame(results)

# Save to CSV
output_df.to_csv("ip_enriched_output.csv", index=False)

print("\nDONE! File created: ip_enriched_output.csv")
output_df